import type { Metadata } from "next";
import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import AppSideBar from "./components/app-sidebar";

import { Toaster } from "sonner";
import { QueryClientProvider } from "@tanstack/react-query";
import ReactQueryProvider from "@/provider/react-query-provider";
import SheetSalerRegister from "./components/sheet-saler-register";
import ToogleThemeButton from "./components/toogle-theme";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const popinsFont = Poppins({
  subsets: ["latin"],
  variable: "--font-poppins",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={`${popinsFont.className} antialiased`}>
        <SidebarProvider>
          <AppSideBar />
          <main className="w-screen h-screen">
            <ReactQueryProvider>
              <div className="flex flex-row h-12 p-3 w-full justify-between border items-center">
                <p className="font-semibold text-sm">Tela de Produtos</p>
                <div className="flex flex-row gap-2 justify-center items-center">
                  <ToogleThemeButton />
                  <SheetSalerRegister />
                </div>
              </div>
              {children}
            </ReactQueryProvider>
          </main>
        </SidebarProvider>
        <Toaster />
      </body>
    </html>
  );
}
